#pragma once

#include <cassert>
#include <optional>
#include <string>

/* contdown from 1024 for tokens not generated by bison */
const int COMMENT = 1023;
const int MULTI_LINE_COMMENT = 1022;

class Token {
public:
  using Type = int;

  Token(int line, Type type, std::string &&str);

  Type type() const { return type_; }

  std::string value() { return value_; }

  const char *type_str() const;

  int line() { return line_; }

private:
  Type type_;
  std::string value_;
  int line_;
};

inline bool is_comment(Token::Type type) {
  return type == COMMENT || type == MULTI_LINE_COMMENT;
}
