#pragma once

#include <optional>
#include <string>
enum {
  IF,
  ELSE,
  FOR,
  WHILE,
  DO,
  BREAK,
  INT,
  CHAR,
  FLOAT,
  DOUBLE,
  VOID,
  RETURN,
  SWITCH,
  CASE,
  DEFAULT,
  CONTINUE,
  CONST_INT,
  CONST_FLOAT,
  CONST_CHAR,
  ADDOP,
  MULOP,
  INCOP,
  RELOP,
  ASSIGNOP,
  LOGICOP,
  BITOP,
  NOT,
  LPAREN,
  RPAREN,
  LCURL,
  RCURL,
  LSQUARE,
  RSQUARE,
  COMMA,
  SEMICOLON,
  ID,
  STRING,
  MULTI_LINE_STRING
};
/* contdown from 1024 for tokens not generated by bison */
const int COMMENT = 1023;
const int MULTI_LINE_COMMENT = 1022;

class Token {
public:
  using Type = int;

  Token(Type type);
  Token(Type type, std::string &&str);
  Token(Type type, std::string_view str);

  Type type() const { return type_; }

  std::optional<std::string_view> value() { return value_; }

  const char *type_str() const;

private:
  Type type_;
  std::optional<std::string> value_;
};

inline bool is_comment(Token::Type type) {
  return type == COMMENT || type == MULTI_LINE_COMMENT;
}
